### ISSUE TITLE
node_modules не трябва да се commit-ва

### ISSUE THREAD

**Issue by profjordanov** [DarkFirePhoenixX/HybridTech-Homework#1]
Здравей, погледнах https://github.com/DarkFirePhoenixX/HybridTech-Homework/tree/main/Exercise%207
хубаво е да се изтрие [node_modules](https://github.com/DarkFirePhoenixX/HybridTech-Homework/tree/main/Exercise%207/node_modules) и да се добави [.gitignore](https://github.com/DarkFirePhoenixX/HybridTech-Homework/blob/main/Exercise%206/.gitignore) подобно на 06 и 05.

**Comment by DarkFirePhoenixX** [comment]
Благодаря, погледнах и оправих проблемите.

На ср, 19.04.2023 г., 09:36 ч. Jordan Jordanov ***@***.***>
написа:
